version: "3"
# define services that make up the applicaiton
services:
  app:
    build:
      # . (current directory)
      context: .

    ports:
      - "8000:8000" # mapping our host port 8000 to docker image

    volumes:
      - ./app:/app  # this maps any changes in any file from our local computer to our docker container

    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
