from django.urls import path, include
# the default router is a feature of the django rest_framework and will
# automatically generate the urls for our viewset. So when you have a viewset,
# you may have multiple urls associated with that ONE viewset. The router
# auto registers the apporiate urls for all of the actions in our viewset
from rest_framework.routers import DefaultRouter
from recipe import views


# create a new router object
router = DefaultRouter()
# register our view
router.register('tags', views.TagViewSet)
router.register('ingredients', views.IngredientViewSet)
# define the app name so that the reverse function can look up correct urls
app_name = 'recipe'

urlpatterns = [
    # all of the urls that our generated by our default router
    # will be included in the url patterns.
    path('', include(router.urls))
]
